export const metadata = {
  title: 'Victoria & Jude • 13.12.2025 • Ibadan, Nigeria',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
